### ISSUE TITLE
Name in Modulefile is incorrect

### ISSUE THREAD

**Issue by razorsedge** [shr3kst3r/puppet-vagrant#1]
The name of this module should be "vagrant" since the class name is `class vagrant`.  Please update file `Modulefile` `name 'puppet-vagrant'` to be `name 'shr3kst3r-vagrant'`.

**Comment by shr3kst3r** [comment]
I updated the name.  Thanks for catching this.  Let me know if I screwed this or something else up. :)  I also bumped the version.

**Comment by razorsedge** [comment]
@shr3kst3r : Now I think that the name on the Forge is incorrect: `puppet module install shr3kst3r/puppet_vagrant` results in a directory `puppet_vagrant` which does not match the class name in `init.pp`.

**Comment by shr3kst3r** [comment]
So, it looks like I really screwed this up.  What I ended up doing was creating a new module on the forge with the correct name.  The new module can be found here: http://forge.puppetlabs.com/shr3kst3r/vagrant.  I need to figure out what to do with the old module.
